title: Practice Makes Perfect
description: My Personal Blog
author: Masaki Samejima
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/harusametime
about: 
disqus_shortname: harusametime
google_analytics: 
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Github
      url: https://github.com/harusametime
      icon: fa-github
    - text: twitter
      url: http://twitter.com/harusametime
      icon: fa-twitter
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      
social:
      

enableTags: true
tagarray: []

url: "http://harusametime.github.io"
baseurl: "/blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
